# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionC', models.CharField(max_length=350)),
                ('fechaC', models.DateTimeField(verbose_name='fecha comentario')),
                ('autorC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloT', models.CharField(max_length=100)),
                ('descripcionT', models.CharField(max_length=350)),
                ('fechaT', models.DateTimeField(verbose_name='fecha ticket')),
                ('autorT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor Ticket+', to=settings.AUTH_USER_MODEL)),
                ('categoriaT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
                ('responsableT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable Ticket+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ticket'),
        ),
    ]
